import { Works, type Work } from './works';
const gallery: Work[] = [
	Works.Maids,
	Works.SleepingInBlueberries,
	Works.PomegranatesBotticelli,
	Works.FallenAngel,
	Works.Butcher,
	Works.NoCoffee,
	Works.Harpocrates,
	Works.Piebald,
	Works.Ra,
	Works.LaceAndLingerie,
	Works.FishBones,
	Works.Petrichor,
	Works.SelfPortrait,
	Works.Death,
	Works.Romeyn,
	Works.Maiden,
	Works.HeliosSelene,
	Works.AphroditeAres,
	Works.Squid,
	Works.StopNoHare,
	Works.SiTianWang,
	Works.DuoWenTianWang,
	Works.PedestrianSitting,
	Works.LitterAheadLilith,
	Works.StopHorny,
	Works.TwilightZone,
	Works.FindingSelf,
	Works.WarOnWomen,
	Works.PicnicHere,
	Works.RedVelvet,
	Works.Carousel,
	Works.TibetanChamMask1,
	Works.TibetanChamMask2,
	Works.TibetanChamMask3,
	Works.FragmentsOfSussex,
	Works.Greed,
	Works.Marzanna
].sort((a: Work, b: Work) => b.year - a.year);
export default gallery;
